services:
  webhook:
    image: docker pull ghcr.io/kth-biblioteket/kthb-webhook-docker:main 
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    container_name: webhook
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/kthb/docker:/docker:ro
    restart: always
    networks:
      - "apps-net"

networks:
  apps-net:
    external: true